### ISSUE TITLE
Make Java 8 baseline

### ISSUE THREAD

**Issue by sormuras** [sormuras/junit-platform-maven-plugin#10]
Transform artifact into a multi-release JAR to support Java 8 as baseline.

@rfscholte Does `maven-compiler-plugin` 3.8.0 already support this?

**Comment by sormuras** [comment]
I tend to decline this "enhancement" for now and stick with Java 10 or even 11. Surefire is doing a good job for supporting Java 8 based projects that use the JUnit Platform since version 2.22.0.

**Comment by rfscholte** [comment]
https://maven.apache.org/plugins/maven-compiler-plugin/multirelease.html

**Comment by sormuras** [comment]
Yes. But... the wall of text and the amount of options presented their... were too much. I thought there was default/standard way how to layout such a mr-project that the "compiler" and "jar" plugins support auto-magically. ;-)

**Comment by rfscholte** [comment]
No, there's no optimal solution, see the matrix. Based on  your requirements you have to make a choice. See https://github.com/apache/maven-compiler-plugin/tree/master/src/it/multirelease-patterns. Personally I'm quite pleased with `singleproject-runtime`

**Comment by sormuras** [comment]
Alright. Do you (or `maven-compiler-plugin`) have an example for `singleproject-runtime` layout and configuration at hand?

**Comment by rfscholte** [comment]
You didn't hit the multirelease-patterns link, right? Those are verified as they are also executed as integration tests. Plexus-Java uses this pattern as well.

**Comment by sormuras** [comment]
Ups. My fault, openend the link in the background and didn't read it. Was focussed on the matrix page.., and browsing your commits at https://github.com/apache/maven-compiler-plugin/commits/MCOMPILER-320

Now, onto the "multirelease-patterns". Thanks, Robert!

**Comment by sormuras** [comment]
Looked at the examples and like the `singleproject-runtime` too, Robert.

But I still tend to target Java 11+ only. Keeping the setup plain and simple.

**Comment by sormuras** [comment]
Staying on 10. Moving to 11, soon.

**Comment by sormuras** [comment]
Adopt multi-module setup from https://github.com/sormuras/mainrunner to allow execution on Java 8 as well.
