### ISSUE TITLE
How to exclude specific package from test run

### ISSUE THREAD

**Issue by nilic10** [sormuras/junit-platform-maven-plugin#109]
Hi,

I'm trying to exclude some specific package when running all my the tests. Is there some property I can use it ?

Thanks

**Comment by sormuras** [comment]
No, there's no direct package filter support in this plugin.

I guess, you're looking for something in the line of JUnit's consoler launcher option, right?
```
      --exclude-package=PKG  Provide a package to be excluded from the test run. This option
                               can be repeated.
```

You could either come up with a regular expression and configure a special class name pattern: https://github.com/sormuras/junit-platform-maven-plugin#class-name-patterns

Or implemented and register a post discovery filter: https://junit.org/junit5/docs/current/user-guide/#launcher-api-post-discovery-filters-custom

**Comment by nilic10** [comment]
Right, but how to set class name pattern for excluding all tests from some package ?
Can you write some example, please ?

**Comment by sormuras** [comment]
Have a look at: https://stackoverflow.com/questions/2078915/a-regular-expression-to-exclude-a-word-string

**Comment by nilic10** [comment]
fixed by adding tags.
Closing issue
