### ISSUE TITLE
Surefire migration support

### ISSUE THREAD

**Issue by sormuras** [sormuras/junit-platform-maven-plugin#23]
Parse `maven-surefire-plugin` configuration and map it to `junit-platform-maven-plugin`'s options.

**Comment by monperrus** [comment]
What are the key advantages of `junit-platform-maven-plugin` over surefire?

**Comment by sormuras** [comment]
Thanks for reaching out, Martin.

In addition to the [key features](https://github.com/sormuras/junit-platform-maven-plugin#features), this plugin
- doesn't carry any legacy "framework binding" code, it delegates all "framework abstractions" to the JUnit Platform and it's test engines,
- and it can be built within [minutes](https://travis-ci.com/sormuras/junit-platform-maven-plugin/builds) instead of [hours](https://builds.apache.org/job/maven-box/job/maven-surefire/).

**Comment by monperrus** [comment]
Thanks!

**Comment by sormuras** [comment]
Done for some entries via https://github.com/sormuras/junit-platform-maven-plugin/commit/89e10e47c1533bf33b8bf699059be7e2391cb251 -- if you need more, please open a new issue.

**Comment by monperrus** [comment]
thanks!

**Comment by sormuras** [comment]
Find all supported configuration elements here: [SurefireMigrationSupport.java](https://github.com/sormuras/junit-platform-maven-plugin/blob/master/src/main/java/de/sormuras/junit/platform/maven/plugin/SurefireMigrationSupport.java)
