### ISSUE TITLE
Informational log as warning when using a junit-platform.properties file.

### ISSUE THREAD

**Issue by TomerFi** [sormuras/junit-platform-maven-plugin#52]
Hey

Great plugin!

I'm using a `junit-platform.properties` file in my test resources folder with the following content:

```text
junit.jupiter.displayname.generator.default = org.junit.jupiter.api.DisplayNameGenerator$ReplaceUnderscores
```

I get these `INFO` log lines disguised as `WARNING` log lines.

```text
[WARNING] Oct 18, 2020 5:53:17 PM org.junit.platform.launcher.core.LauncherConfigurationParameters loadClasspathResource
[WARNING] INFO: Loading JUnit Platform configuration parameters from classpath resource [file:/C:/.../target/test-classes/junit-platform.properties].
[WARNING] Oct 18, 2020 5:53:17 PM org.junit.platform.launcher.core.LauncherConfigurationParameters loadClasspathResource
[WARNING] INFO: Loading JUnit Platform configuration parameters from classpath resource [file:/C:/.../junit-platform.properties].
[WARNING] Oct 18, 2020 5:53:17 PM org.junit.jupiter.engine.config.InstantiatingConfigurationParameterConverter logSuccessMessage
[WARNING] INFO: Using default display name generator 'org.junit.jupiter.api.DisplayNameGenerator$ReplaceUnderscores' set via the 'junit.jupiter.displayname.generator.default' configuration parameter.
```

Removing the `junit-platform.properties`  will of course get rid of these messages.

Is there any way to suppress these warnings?

**Comment by sormuras** [comment]
Thanks Tomer.

The `junit-platform-maven-plugin` collects messages from normal (expected) and error output streams. Messages collected from the error stream are passed on as warnings.

IIRC, the default JUL implementation prints those "two lines per message" on the error stream. When you configure JUL to use the normal stream for its output those messages will stay visible, but marked as "info".
Or you raise the threshold of `org.junit.*` log level to warning to suppress the "INFO" statements being generated in the first place.

**Comment by TomerFi** [comment]
@sormuras 
Thank you very much for your response.
I was able to accomplish what I needed based on your recommendations.

The thing is,
To set the required loggers level to warning,
I added the following properties file:

```text
handlers= java.util.logging.ConsoleHandler
.level= ALL
java.util.logging.ConsoleHandler.level = INFO
org.junit.platform.launcher.core.LauncherConfigurationParameters.level = WARNING
org.junit.jupiter.engine.config.InstantiatingConfigurationParameterConverter.level = WARNING
```

To load the file,
I used `maven-surefire-plugin` to set the associated system property:

```xml
<plugin>
  <artifactId>maven-surefire-plugin</artifactId>
  <version>${maven-surefire-plugin.version}</version>
  <configuration>
    <systemPropertyVariables>
      <java.util.logging.config.file>src/test/resources/logging-test.properties</java.util.logging.config.file>
    </systemPropertyVariables>
  </configuration>
</plugin>
```

Can you perhaps think of another way to accomplish that without using `maven-surefire-plugin`?

**Comment by sormuras** [comment]
I guess, you're using the `JAVA` executor. If so, you may pass [additional options](https://github.com/sormuras/junit-platform-maven-plugin#executor-java) via the `javaOptions` element.

Something like scratched below should work:

```xml
<configuration>
  <executor>JAVA</executor>
  <javaOptions>
    <additionalOptions>
      <additionalOption>java.util.logging.config.file</additionalOption>
      <additionalOption>src/test/resources/logging-test.properties</additionalOption>
    </additionalOptions>
  </javaOptions>
</configuration>
```

**Comment by TomerFi** [comment]
@sormuras 👌

Thank you very much!
That did the trick with a minor adjustment:

```xml
<configuration>
  <executor>JAVA</executor>
  <javaOptions>
    <additionalOptions>
      <additionalOption>-Djava.util.logging.config.file=src/test/resources/logging-test.properties</additionalOption>
    </additionalOptions>
  </javaOptions>
</configuration>
```

**Comment by sormuras** [comment]
Excellent!

For the record, I missed the  `-D` in my example. It should work with separate arguments as well:

```xml
<configuration>
  <executor>JAVA</executor>
  <javaOptions>
    <additionalOptions>
      <additionalOption>-Djava.util.logging.config.file</additionalOption>
      <additionalOption>src/test/resources/logging-test.properties</additionalOption>
    </additionalOptions>
  </javaOptions>
</configuration>
```
