### ISSUE TITLE
Build error if skipping JaCoCo

### ISSUE THREAD

**Issue by dbwiddis** [sormuras/junit-platform-maven-plugin#63]
First, I want to thank you for this fantastic plugin! I've been fighting "testing in the modular world" (despite reading your blog) for a good portion of a year now, and finally noticed this plugin in the fine print. It's a life saver!

I did run into a small issue integrating JaCoCo, but found the `jacoco-executor-java` on your site and it worked well adding this configuration to your plugin:
```
<executor>JAVA</executor>
<javaOptions>
	<additionalOptions>
		<jacoco>${jacoco.java.option}</jacoco>
	</additionalOptions>
</javaOptions>
```
with that property defined in the jacoco plugin's config:
```
<configuration>
	<propertyName>jacoco.java.option</propertyName>
</configuration>
```
Everything works beautifully on `mvn test`.

However, on my CI platforms, I try to save processing time by skipping the JaCoCo report if I'm not going to send it anywhere, using the command line `mvn test -B -Djacoco.skip=true`.   This, however, fails:
```
[INFO] --- junit-platform-maven-plugin:1.1.0:launch (injected-launch) @ oshi-core ---
[INFO] Launching JUnit Platform 1.7.1...
[ERROR] Error: Could not find or load main class 
```
Relevant stack trace line:
```
[ERROR] Failed to execute goal de.sormuras.junit:junit-platform-maven-plugin:1.1.0:launch (injected-launch) on project oshi-core: RED ALERT! -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal de.sormuras.junit:junit-platform-maven-plugin:1.1.0:launch (injected-launch) on project oshi-core: RED ALERT!
...
Caused by: org.apache.maven.plugin.MojoFailureException: RED ALERT!
    at de.sormuras.junit.platform.maven.plugin.JUnitPlatformMojo.execute (JUnitPlatformMojo.java:434)
```
I suspect the property name isn't being set when JaCoCo is skipped, and I'm not sure what behind the scenes black magic requires that field anyway.

I can obviously work around this by not skipping JaCoCo in my CI builds, but I'm curious if there's a way to make the plugin more robust to a command line on-off switch for JaCoCo.

**Comment by sormuras** [comment]
Hi Daniel, thank you for using this plugin and reporting an issue in great detail.

As a second workaround, could you please try to preset a value for the `jacoco.java.option` property that always works with `java`? Perhaps, that a) by-passes the issue when JaCoCo is skippend and b) it gets overridden when JaCoCo is executed.

Otherwise, it would be great to have a copy of [it/jacoco-executor-java](https://github.com/sormuras/junit-platform-maven-plugin/tree/master/src/it/jacoco-executor-java) that calls Maven with `-Djacoco.skip=true` to reproduce the issue. Do you want create PR for this?

**Comment by sormuras** [comment]
Added an IT here: https://github.com/sormuras/junit-platform-maven-plugin/tree/master/src/it/jacoco-executor-java-skipped

It calls Maven via

https://github.com/sormuras/junit-platform-maven-plugin/blob/cfa32a316d31830087177528538b107dd9597576/src/it/jacoco-executor-java-skipped/invoker.properties#L2

and does **not** preset a value for `jacoco.java.option`:

https://github.com/sormuras/junit-platform-maven-plugin/blob/cfa32a316d31830087177528538b107dd9597576/src/it/jacoco-executor-java-skipped/pom.xml#L23-L25

Can you please try to make it fail?

**Comment by sormuras** [comment]
🤔 

Works on my machine, fails on GH Actions: https://github.com/sormuras/junit-platform-maven-plugin/runs/1948899680?check_suite_focus=true#step:6:498

**Comment by sormuras** [comment]
Gotcha. It's the empty Java Agent line!

```
[DEBUG] Starting process...
[DEBUG] /opt/hostedtoolcache/jdk/11.0.10/x64/bin/java
[DEBUG] -javaagent:/home/.../org.jacoco.agent-0.8.6-runtime.jar=destfile=/home/.../jacoco.exec
[DEBUG] -enableassertions
...
```

vs

```
[DEBUG] Starting process...
[DEBUG] /opt/hostedtoolcache/jdk/11.0.10/x64/bin/java
[DEBUG] 
[DEBUG] -enableassertions
...
```

**Comment by sormuras** [comment]
Released version `1.1.2` that contains a fix for this issue.

**Comment by dbwiddis** [comment]
I suppose I could have offered my debug log with that insight too:
```
[DEBUG] 
[DEBUG] Starting process...
[DEBUG] /usr/local/jdk-1.8.0/jre/bin/java
[DEBUG] 
[DEBUG] -enableassertions
[DEBUG] -Dfile.encoding=UTF-8
[DEBUG] -classpath
...
```
Thanks for the fix, confirmed it solves the problem (Now to figure out how to disable the global timeout but I'm sure I saw that somewhere. 😄 )

**Comment by sormuras** [comment]
https://github.com/sormuras/junit-platform-maven-plugin#global-timeout 😉

**Comment by dbwiddis** [comment]
Yeah, found it quickly searching for "300". :-)

But there is no `<progressBar>true</progressBar>` option yet for us impatient types who want to know just a little bit what's going on while there's no output.   Maybe I'll try to figure out how to add that. 😃
