### ISSUE TITLE
Upgrading slf4j dependency breaks junit-platform-console on hamcrest dependency

### ISSUE THREAD

**Issue by dbwiddis** [sormuras/junit-platform-maven-plugin#67]
If the subject line sounds confusing, it is to me too.  I'm not even sure this is the right project to which to submit this issue, but since the error is occurring during execution of this plugin, it's at least a cry for help from someone who might have an inkling where else I can look!

Background:
 - My project targets support for JDK 8 and everything works fine there 
   - I have a runtime dependency on SLF4J (1.7.30, trying to upgrade)
 - My tests are set up using the same package name in a test directory
   - I have test dependencies on junit-jupiter-api (5.7.1) and hamcrest (2.2)
 - I publish a separate artifact which simply adds the module-info.java class 
   - I'm using the junit-platform-maven-plugin and the module-info.test approach outlined in your fantastic "testing in the modular world" document, which makes everything work in JDK 11+

The change causing problems:
 - A [user requested](https://github.com/oshi/oshi/issues/1575) that I upgrade SLF4J to the version which contains a module descriptor, currently 2.0.0-alpha1.  Despite the alpha name/unstable categorization, it's in wide usage.
 - Simply changing the version of SLF4J breaks the Junit class loading on the hamcrest test dependency
   - I can't find any logical reason why this would happen.  There's no dependency relationship between these two projects
   - There's only one guess/hunch that I have: before this change, there are non-modular projects on the classpath/unnamed module. With this change, all dependencies have either a module name, or in the case of hamcrest, an automatic module name. 
     - I don't know enough about modulepath, classpath, and automatic module names to know whether that's relevant 

The symptoms:
 - When running any maven command invoking tests (test, verify, install, deploy, etc.) the junit-platform-maven-plugin fails with messages like the below (middle bits redacted for brevity):
```
[INFO] Launching JUnit Platform 1.7.1...
[ERROR] 
[ERROR] Thanks for using JUnit! Support its development at https://junit.org/sponsoring
[ERROR] 
[ERROR] Usage: ConsoleLauncher [-h] [--disable-ansi-colors] [--disable-banner]
<snip>
[ERROR] org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
[ERROR] 	at org.junit.platform.launcher@1.7.1/org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:111)
<snip>
[ERROR] Caused by: org.junit.platform.commons.JUnitException: ModuleSelector [moduleName = 'com.github.oshi'] resolution failed
[ERROR] 	at org.junit.platform.launcher@1.7.1/org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
<snip>
[ERROR] Caused by: java.lang.NoClassDefFoundError: org/hamcrest/Matcher
[ERROR] 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
<snip>
[ERROR] Caused by: java.lang.ClassNotFoundException: org.hamcrest.Matcher
[ERROR] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
```
Reviewing debug logs, hamcrest is included on the module path:
```
[DEBUG] /usr/local/Cellar/openjdk/15.0.2/libexec/openjdk.jdk/Contents/Home/bin/java
[DEBUG] -javaagent:/Users/danielwiddis/.m2/repository/org/jacoco/org.jacoco.agent/0.8.6/org.jacoco.agent-0.8.6-runtime.jar=destfile=/Users/danielwiddis/git/oshi/oshi-core/target/jacoco.exec,excludes=**/driver/**:**/common/**:**/Abstract*:**/platform/**:**/linux/**:**/mac/**:**/windows/**:**/unix/**:**/demo/**
[DEBUG] -enableassertions
[DEBUG] -Dfile.encoding=UTF-8
[DEBUG] --module-path
[DEBUG] /Users/danielwiddis/.m2/repository/net/java/dev/jna/jna-jpms/5.8.0/jna-jpms-5.8.0.jar:/Users/danielwiddis/.m2/repository/net/java/dev/jna/jna-platform-jpms/5.8.0/jna-platform-jpms-5.8.0.jar:/Users/danielwiddis/.m2/repository/org/slf4j/slf4j-api/2.0.0-alpha1/slf4j-api-2.0.0-alpha1.jar:/Users/danielwiddis/.m2/repository/org/slf4j/slf4j-simple/2.0.0-alpha1/slf4j-simple-2.0.0-alpha1.jar:/Users/danielwiddis/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.7.1/junit-jupiter-api-5.7.1.jar:/Users/danielwiddis/.m2/repository/org/apiguardian/apiguardian-api/1.1.0/apiguardian-api-1.1.0.jar:/Users/danielwiddis/.m2/repository/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar:/Users/danielwiddis/.m2/repository/org/junit/platform/junit-platform-commons/1.7.1/junit-platform-commons-1.7.1.jar:/Users/danielwiddis/.m2/repository/org/hamcrest/hamcrest/2.2/hamcrest-2.2.jar:/Users/danielwiddis/git/oshi/oshi-core/target/junit-platform/patched-test-runtime:/Users/danielwiddis/.m2/repository/org/junit/platform/junit-platform-launcher/1.7.1/junit-platform-launcher-1.7.1.jar:/Users/danielwiddis/.m2/repository/org/junit/platform/junit-platform-engine/1.7.1/junit-platform-engine-1.7.1.jar:/Users/danielwiddis/.m2/repository/org/junit/platform/junit-platform-reporting/1.7.1/junit-platform-reporting-1.7.1.jar:/Users/danielwiddis/.m2/repository/org/junit/platform/junit-platform-console/1.7.1/junit-platform-console-1.7.1.jar:/Users/danielwiddis/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.7.1/junit-jupiter-engine-5.7.1.jar
```
I've looked for split modules and other dependency conflicts.  Nothing abnormal:
```
[INFO] --- maven-dependency-plugin:3.1.2:tree (default-cli) @ oshi-core-java11 ---
[INFO] com.github.oshi:oshi-core-java11:jar:5.7.1-SNAPSHOT
[INFO] +- net.java.dev.jna:jna-jpms:jar:5.8.0:compile
[INFO] +- net.java.dev.jna:jna-platform-jpms:jar:5.8.0:compile
[INFO] +- org.slf4j:slf4j-api:jar:2.0.0-alpha1:compile
[INFO] +- org.slf4j:slf4j-simple:jar:2.0.0-alpha1:test
[INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.7.1:test
[INFO] |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
[INFO] |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  \- org.junit.platform:junit-platform-commons:jar:1.7.1:test
[INFO] \- org.hamcrest:hamcrest:jar:2.2:test
```

Things I've tried with no success:
 - Moved hamcrest earlier in dependency list: no change
 - Adding `requires org.hamcrest` to my module-info.java: Compile error: `module not found: org.hamcrest`
   - To fix above, changing scope from test to compile:  Split module: Every test class tries to run and fails with multiple compilation problems: `The package org.hamcrest is accessible from more than one module: <unnamed>, org.hamcrest`
 - Adding `--add-reads com.github.oshi=org.hamcrest` to the module-info.test file:  Same symptoms as long list above, but the line just before the stack trace says "WARNING: Unknown module: org.hamcrest specified to --add-reads"

I don't know if this is a bug or user (me) error or just a need for a configuration setting in maven.

Happy to try any other suggestions and provide any other output needed.  Or you can try playing with it yourself on the java11 branch here: https://github.com/oshi/oshi/tree/java11

**Comment by sormuras** [comment]
Hi Daniel, I'll try to take a look later this week. I skimmed the configuration and it looks good to me:

https://github.com/oshi/oshi/blob/9fbccfb3a4c71fb714e012f3d8fc33f03eaa1075/pom.xml#L261-L280

**Comment by sormuras** [comment]
3 weeks ... and still got not time. Soon™️...

**Comment by dbwiddis** [comment]
Your definition of "Soon™️" may need recalibrating.  😁 

I was bored enough today to try to debug this myself, and after a few hours of trial and error and stack trace digesting, I managed to get it working by adding the following lines to `module-info.test`:
```
--add-modules 
  org.hamcrest
--add-reads
  com.github.oshi=org.hamcrest
```

So I *think* this was just a configuration thing on my end that I needed to fix.
