### ISSUE TITLE
Additional Custom Configuration Parameters are not working

### ISSUE THREAD

**Issue by TomerFi** [sormuras/junit-platform-maven-plugin#84]
It looks like the _Additional Custom Configuration Parameters_ are not working well.
In [this playground repo](https://github.com/TomerFi/junit-plugin-params-playground) we have two maven projects and one [CI workflow](https://github.com/TomerFi/junit-plugin-params-playground/runs/4595791980?check_suite_focus=true) to test them:

-------------------------------------

The first project is [params_in_plugin](https://github.com/TomerFi/junit-plugin-params-playground/tree/main/params_in_plugin),
the custom configuration parameters are configured in the [plugin configuration](https://github.com/TomerFi/junit-plugin-params-playground/blob/main/params_in_plugin/pom.xml#L50):

```xml
<parameters>
    <junit.jupiter.execution.parallel.enabled>true</junit.jupiter.execution.parallel.enabled>
    <junit.jupiter.execution.parallel.mode.default>concurrent</junit.jupiter.execution.parallel.mode.default>
    <junit.jupiter.displayname.generator.default>org.junit.jupiter.api.DisplayNameGenerator$ReplaceUnderscores</junit.jupiter.displayname.generator.default>
</parameters>
```

As seen in the _Test project with the plugin configuration (not working)_ step in the  [CI workflow](https://github.com/TomerFi/junit-plugin-params-playground/runs/4595791980?check_suite_focus=true),
the test cases are not executed concurrently and the name generation strategy did not take place:

```text
[INFO] --- junit-platform-maven-plugin:1.1.5:launch (injected-launch) @ junit-plugin-params-playground ---
[INFO] Launching JUnit Platform 1.8.2...
[INFO] Output Log: 984 bytes, Error Log: 0 bytes
[INFO] test method number 1 start, thread name: main
[INFO] test method number 1 end, thread name: main
[INFO] test method number 2 start, thread name: main
[INFO] test method number 2 end, thread name: main
[INFO] 
[INFO] Thanks for using JUnit! Support its development at https://junit.org/sponsoring
[INFO] 
[INFO] .
[INFO] '-- JUnit Jupiter [OK]
[INFO]   '-- Class_Name_Underscores_Not_Replaced_Test [OK]
[INFO]     +-- test_number_one() [OK]
[INFO]     '-- test_number_two() [OK]
```

-------------------------------------

The second project is [params_in_properties](https://github.com/TomerFi/junit-plugin-params-playground/tree/main/params_in_properties),
the custom configuration parameters are configured in the [junit-platform.properties resource](https://github.com/TomerFi/junit-plugin-params-playground/blob/main/params_in_properties/src/test/resources/junit-platform.properties):

```properties
junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.mode.default=concurrent
junit.jupiter.displayname.generator.default=org.junit.jupiter.api.DisplayNameGenerator$ReplaceUnderscores
```

As seen in the _Test project with the properties file (working)_ step in the  [CI workflow](https://github.com/TomerFi/junit-plugin-params-playground/runs/4595791980?check_suite_focus=true),
the test cases run concurrently and the names generation works well:

```text
[INFO] --- junit-platform-maven-plugin:1.1.5:launch (injected-launch) @ junit-plugin-params-playground ---
[INFO] Launching JUnit Platform 1.8.2...
[INFO] Output Log: 1,056 bytes, Error Log: 0 bytes
[INFO] test method number 2 start, thread name: ForkJoinPool-1-worker-3
[INFO] test method number 1 start, thread name: ForkJoinPool-1-worker-1
[INFO] test method number 2 end, thread name: ForkJoinPool-1-worker-3
[INFO] test method number 1 end, thread name: ForkJoinPool-1-worker-1
[INFO] 
[INFO] Thanks for using JUnit! Support its development at https://junit.org/sponsoring
[INFO] 
[INFO] .
[INFO] '-- JUnit Jupiter [OK]
[INFO]   '-- Class Name Underscores Not Replaced Test [OK]
[INFO]     +-- test number two [OK]
[INFO]     '-- test number one [OK]
```

**Comment by sormuras** [comment]
Parameters should be passed by

https://github.com/sormuras/junit-platform-maven-plugin/blob/75be966af1075415414a266aac034188ba58714d/src/main/java/de/sormuras/junit/platform/maven/plugin/JavaExecutor.java#L239

to the launcher when using the Java executor.

**Comment by sormuras** [comment]
```text
[DEBUG] Starting process...
[DEBUG] D:\dev\jdk\jdk-17.0.1\bin\java.exe
[DEBUG] -enableassertions
[DEBUG] -Dfile.encoding=UTF-8
[DEBUG] -classpath
[...]
[DEBUG] org.junit.platform.console.ConsoleLauncher
[DEBUG] --fail-if-no-tests
[DEBUG] --details
[DEBUG] tree
[DEBUG] --details-theme
[DEBUG] ascii
[DEBUG] --reports-dir
[...]
[DEBUG] --include-tag="bar"
[DEBUG] --include-tag="foo"
[DEBUG] --config="junit.jupiter.execution.parallel.enabled"="true"
[DEBUG] --config="ninety.nine"="99"
[DEBUG] --scan-class-path
[DEBUG] Process started: Process[pid=3556, exitValue="not exited"]
```
Maybe the wrapping `"`-characters aren't elided? 🤔

**Comment by TomerFi** [comment]
@sormuras 
Yes, you are right.
Removing it fixes the issue.

Can I push?

**Comment by TomerFi** [comment]
It appears that the tags don't like the `"` too.

**Comment by TomerFi** [comment]
https://github.com/sormuras/junit-platform-maven-plugin/pull/85 removes the redundant `"` from the parameters and the tags.
I've tested this locally and added an integration test called `configured-java-executor`, based on the existing `configured` one.

This PR doesn't address the selectors not being implemented by the `JavaExecutor`,
it looks like a separate concern, I'll open another issue and perhaps another PR this weekend.
